zen.lib.tech.replaceRecipeUnlock("speed-module", "speed-module", "speed-module-0")
zen.lib.tech.addRecipeUnlock("speed-module", "speed-module-0-harness")
zen.lib.tech.replaceRecipeUnlock("productivity-module", "productivity-module", "productivity-module-0")
zen.lib.tech.addRecipeUnlock("productivity-module", "productivity-module-0-harness")
zen.lib.tech.replaceRecipeUnlock("effectivity-module", "effectivity-module", "effectivity-module-0")
zen.lib.tech.addRecipeUnlock("effectivity-module", "effectivity-module-0-harness")

zen.lib.tech.replacePrereq("modules", "advanced-electronics", "electronics")
zen.lib.tech.addRecipeUnlock("modules", "basic-module-contact")
zen.lib.tech.addRecipeUnlock("modules", "module-processor-0")

zen.lib.tech.addRecipeUnlock("speed-module",   "speed-module-processor-0")
zen.lib.tech.addRecipeUnlock("speed-module-2", "speed-module-processor-1")
zen.lib.tech.addRecipeUnlock("speed-module-4", "speed-module-processor-2")
zen.lib.tech.addRecipeUnlock("speed-module-6", "speed-module-processor-3")

zen.lib.tech.addRecipeUnlock("productivity-module",   "productivity-module-processor-0")
zen.lib.tech.addRecipeUnlock("productivity-module-2", "productivity-module-processor-1")
zen.lib.tech.addRecipeUnlock("productivity-module-4", "productivity-module-processor-2")
zen.lib.tech.addRecipeUnlock("productivity-module-6", "productivity-module-processor-3")

zen.lib.tech.addRecipeUnlock("effectivity-module",   "effectivity-module-processor-0")
zen.lib.tech.addRecipeUnlock("effectivity-module-2", "effectivity-module-processor-1")
zen.lib.tech.addRecipeUnlock("effectivity-module-4", "effectivity-module-processor-2")
zen.lib.tech.addRecipeUnlock("effectivity-module-6", "effectivity-module-processor-3")
