zen.lib.tech.replaceRecipeUnlock("speed-module", "speed-module", "speed-module-0")
zen.lib.tech.addRecipeUnlock("speed-module", "speed-module-0-harness")
-- zen.lib.tech.replaceRecipeUnlock("productivity-module", "productivity-module", "productivity-module-0")
-- zen.lib.tech.addRecipeUnlock("productivity-module", "productivity-module-0-harness")
-- zen.lib.tech.replaceRecipeUnlock("effectivity-module", "effectivity-module", "effectivity-module-0")
-- zen.lib.tech.addRecipeUnlock("effectivity-module", "effectivity-module-0-harness")

zen.lib.tech.replacePrereq("modules", "advanced-electronics", "electronics")
zen.lib.tech.addRecipeUnlock("modules", "basic-module-contact")
zen.lib.tech.addRecipeUnlock("modules", "module-processor-0")
